home/urls.py
from . import views
from django.urls import path

urlpatterns = [
    path('', views.index, name='home'),
]

project_savvy/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("", include("home.urls"), name="home-urls"),
    path("about/", include ("about.urls"), name="about-urls"),
    path("tickets/", include("tickets.urls"), name="tickets"),
    path("accounts/", include("allauth.urls")),
    path("summernote/", include("django_summernote.urls")),
    path("admin/", admin.site.urls),
]

tickets/urls.py
from . import views
from django.urls import path
from .views import (
    TicketListView, TicketDetailView, CreateTicketView, 
    TicketUpdateView, TicketDeleteView, delete_comment, complete_ticket
    )

urlpatterns = [
    path("", TicketListView.as_view(), name="tickets"),
    path('create/', CreateTicketView.as_view(), name='create_ticket'),
    path('<slug:slug>/', TicketDetailView.as_view(), name='ticket_detail'),
    path('<slug:slug>/update/', TicketUpdateView.as_view(), name='update_ticket'),
    path('<slug:slug>/delete/', TicketDeleteView.as_view(), name='delete_ticket'),
    path('delete-comment/<int:comment_id>/', views.delete_comment, name='delete_comment'),
    path('tickets/<slug:ticket_slug>/complete/', views.complete_ticket, name='complete_ticket'),
]

tickets/models.py
from django.db import models
from django.urls import reverse
from django.template.defaultfilters import slugify
from django.contrib.auth.models import User

JOB_CATEGORY = (
    (0, "Plumbing"),
    (1, "Electrical"),
    (2, "Heating"),
    (3, "Cleaning"),
    (4, "Vending Services"),
    (5, "Air Conditioning"),
    (6, "Waste"),
    (7, "Other"),
)

PRIORITY = (
    (0, "High (<2 hours)"),
    (1, "Medium (<1 day)"),
    (2, "Low (1 day +)"),
)

class Ticket(models.Model):
    """Ticket Model"""
    title = models.CharField(max_length=200, unique=True)
    slug = models.SlugField(null=True, unique=True)
    username = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name="user_tickets")
    job_category = models.IntegerField(choices=JOB_CATEGORY, default=0)
    job_description = models.TextField(max_length=400, blank=False)
    created_on = models.DateTimeField(auto_now_add=True)
    location = models.TextField(max_length=200)
    priority = models.IntegerField(choices=PRIORITY, default=0)
    is_complete = models.BooleanField(default=False)
    completed_by = models.ForeignKey(
        User, on_delete=models.SET_NULL, blank=True, null=True,
        related_name="completed_tickets")
    completed_at = models.DateTimeField(null=True, blank=True)
    updated_on = models.DateTimeField(auto_now=True)
    updated_by = models.ForeignKey(
        User, on_delete=models.SET_NULL, null=True, blank=True,
        related_name="updated_tickets")

    class Meta:
        ordering = ["created_on"]

    def __str__(self):
        return f"Request: {self.title}"

    def get_absolute_url(self):
        return reverse("ticket_detail", kwargs={"slug": self.slug})

    def save(self, *args, **kwargs):
        self.slug = slugify(self.title)
        super(Ticket, self).save(*args, **kwargs)

        
class Comment(models.Model):
    """Comment Model"""
    ticket = models.ForeignKey(
        Ticket, on_delete=models.CASCADE, related_name="comments")
    username = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name="commenter")
    body = models.TextField()
    created_on = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ["created_on"]
        
    def __str__(self):
        return f"{self.body} by {self.username}"

tickets/forms.py
from .models import Comment
from django import forms

# Comments form
class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('body',)

tickets/views.py
from django.shortcuts import get_object_or_404, redirect
from django.views.generic import (
    ListView, DetailView, CreateView, UpdateView, DeleteView)
from .models import Ticket, JOB_CATEGORY, PRIORITY, Comment
from .forms import CommentForm
from django.urls import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.utils.timezone import now


class TicketListView(LoginRequiredMixin, ListView):
    """
    Display a paginated list of all created tickets, Users are able to sort 
    by various filters and display only their own tickets
    """
    queryset = Ticket.objects.all()
    template_name = "tickets/tickets.html"
    paginate_by = 6

    def get_queryset(self):
        queryset = super().get_queryset()

        show_own_tickets = self.request.GET.get('own_tickets', False)
        if show_own_tickets:
            queryset = queryset.filter(username=self.request.user)

        sort_by = self.request.GET.get('sort_by', 'priority_high')
        if sort_by == 'priority_high':
            queryset = queryset.filter(is_complete=False).order_by(
                'priority', 'created_on')
        elif sort_by == 'priority_low':
            queryset = queryset.filter(is_complete=False).order_by(
                '-priority', 'created_on')
        elif sort_by == 'created_newest':
            queryset = queryset.filter(is_complete=False).order_by(
                '-created_on', 'priority')
        elif sort_by == 'created_oldest':
            queryset = queryset.filter(is_complete=False).order_by(
                'created_on', 'priority')
        elif sort_by == 'completed':
            queryset = queryset.filter(is_complete=True).order_by(
                '-completed_at', 'created_on')
        else:
            queryset = queryset.order_by('priority', 'created_on')

        return queryset

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['selected_sort_by'] = self.request.GET.get(
            'sort_by', 'priority_high')
        context['show_own_tickets'] = self.request.GET.get(
            'own_tickets', False)
        return context


class TicketDetailView(LoginRequiredMixin, DetailView):
    """
    Individual ticket detailed view with option to add comments to ticket.
    """
    model = Ticket
    template_name = "tickets/ticket_detail.html"
    slug_field = 'slug'

    def get_object(self, queryset=None):
        slug = self.kwargs.get(self.slug_url_kwarg)
        queryset = self.get_queryset()
        return get_object_or_404(queryset, slug=slug)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        ticket = self.object
        context['comments'] = ticket.comments.all()
        context['comment_form'] = CommentForm()
        return context

    def post(self, request, *args, **kwargs):
        ticket = self.get_object()
        body = request.POST.get('body')
        if body:
            comment = Comment.objects.create(
                ticket=ticket, username=request.user, body=body)
            comment.save()
            messages.success(self.request, 'Comment created successfully')
        return redirect('ticket_detail', slug=ticket.slug)


class CreateTicketView(LoginRequiredMixin, CreateView):
    """View to create a new ticket"""
    model = Ticket
    template_name = 'tickets/create_ticket.html'
    fields = [
        'title', 'job_category', 'job_description', 'location', 'priority'
        ]

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['JOB_CATEGORY'] = JOB_CATEGORY
        context['PRIORITY'] = PRIORITY
        return context

    def form_valid(self, form):
        title = form.cleaned_data['title']
        if Ticket.objects.filter(title=title).exists():
            form.add_error('title', 'A ticket with this title already exists.')
            return self.form_invalid(form)
        form.instance.username = self.request.user
        messages.success(self.request, 'Ticket created successfully')
        return super().form_valid(form)

    def get_success_url(self):
        return '/tickets/'


class TicketUpdateView(LoginRequiredMixin, UpdateView):
    """Update Ticket content view"""
    model = Ticket
    template_name = 'tickets/update_ticket.html'
    fields = [
        'title', 'job_category', 'job_description', 'location', 'priority'
        ]

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['JOB_CATEGORY'] = JOB_CATEGORY
        context['PRIORITY'] = PRIORITY
        return context

    def form_valid(self, form):
        form.instance.username = self.request.user
        if form.instance.is_complete:
            form.instance.completed_by = self.request.user
            form.instance.completed_at = now()

        messages.success(self.request, 'Ticket updated successfully')
        return super().form_valid(form)


class TicketDeleteView(LoginRequiredMixin, DeleteView):
    """Delete Ticket View"""
    model = Ticket
    success_url = reverse_lazy('tickets')
    template_name = 'tickets/delete_ticket.html'


@login_required
def delete_comment(request, comment_id):
    """Delete User Comment View"""
    comment = get_object_or_404(Comment, id=comment_id)
    ticket_slug = comment.ticket.slug
    if comment.username == request.user:
        comment.delete()
        messages.success(request, 'Comment deleted successfully.')
    else:
        messages.error(
            request, 'You do not have permission to delete this comment.')
    return redirect('ticket_detail', slug=ticket_slug)


@login_required
def complete_ticket(request, ticket_slug):
    """
    If staff authenticated, View to allow completion of tickets, marking
    ticket as complete and setting a completed timestamp.
    """
    ticket = get_object_or_404(Ticket, slug=ticket_slug)

    if not request.user.is_superuser and not request.user.is_staff:
        messages.error(request, 
        "You do not have permission to complete this ticket.")
        return redirect('ticket_detail', slug=ticket.slug)

    if ticket.is_complete:
        ticket.is_complete = False
        ticket.completed_by = None
        ticket.completed_at = None
        messages.success(request, "Ticket marked as 'Incomplete'")
    else:
        ticket.is_complete = True
        ticket.completed_by = request.user
        ticket.completed_at = now()
        messages.success(request, "Ticket marked as 'Complete'")

    ticket.updated_by = request.user
    ticket.save()

    return redirect('ticket_detail', slug=ticket.slug)

tickets/templates/tickets/create_ticket.html
{% extends "base.html" %}
{% load static %}

{% block content %}
<!--Create a ticket-->
<div class="container">
    <div class="row mt-5">
        <div class="col-md-6">
            <h2 class="mb-2">Create a New Ticket</h2>
            <p>Please provide as much detail as possible to help our team!</p>
            <form method="post" enctype="multipart/form-data">
                {% csrf_token %}
                {% include 'tickets/ticket_form.html' %}
                <button type="submit" class="btn btn-primary my-3" style="background-color:#00856f">Create
                    Ticket</button>
                <div class="col-md-6 text-end mb-4">
                    <a href="{% url 'tickets' %}" class="btn btn-secondary">Cancel</a>
                </div>
            </form>
        </div>
    </div>
</div>

{% endblock content %}

tickets/templates/tickets/create_ticket_list.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Views Part 1</title>
</head>

<body>
    <h1>Tickets</h1>
    {% for create_ticket in object_list %}
    <h2>{{create_ticket.title}}</h2>
    <p>{{ create_ticket.job_category }}</p>
    <p>User: {{create_ticket.username}}</p>
    {% endfor %}
</body>

</html>

tickets/templates/tickets/delete_ticket.html
{% extends "base.html" %}
{% load static %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-8 mt-3 offset-md-2">
            <form method="post">
                {% csrf_token %}
                <p>Are you sure you want to delete this ticket?</p>
                <button type="submit" class="btn btn-danger">Delete</button>
                <a href="{% url 'ticket_detail' ticket.slug %}" class="btn btn-secondary">Cancel</a>
            </form>
        </div>
    </div>
</div>
{% endblock %}

tickets/templates/tickets/edit_comment.html
{% extends "base.html" %}
{% load static %}

{% block content %}
<!--Edit Comment-->
<div class="container">
    <div class="row mt-5">
        <div class="col-md-6">
            <h2 class="mb-2">Edit Comment</h2>
            <form method="post">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit">Save Changes</button>
            </form>
        
            <form method="post" action="#">
                {% csrf_token %}
                <input type="hidden" name="comment_id" value="{{ comment.id }}">
            </form>
                <div class="col-md-6 d-flex justify-content-center">
                    <a href="{% url 'tickets' %}" class="btn btn-secondary my-3">Cancel</a>
                </div>
            </div>
            </form>
        </div>
    </div>
</div>

{% endblock content %}

tickets/templates/tickets/index.html
{% extends "base.html" %}
{% load static %}

{% block content %}

<!-- index.html content starts here -->
<div class="container p-2">
    <div class="row">
        <h1 class="py-2">Tickets</h1>
        <div class="col-sm-12 col-md-4">
            {% for ticket in object_list %}
            <div class="card mb-2">
                <div class="card-body">
                    <a href="{{ tickets.get_absolute_url }}">
                        <h4 class="card-title">{{ ticket.title }}</h4>
                    </a>
                        <p class="text-end mb-0">User: {{ ticket.username }}</p>
                </div>
            </div>
            {% endfor %}
        </div>
        <div class="col-sm-12 col-md-8" style="background-color: aquamarine;">
            <div>
                <h3>Ticket Details</h3>
            </div>
        </div>
    </div>
</div>



<!-- index.html content ends here -->
{% endblock content %}

<!-- Copyright -->
{% block copyright %}
Copyright 2024 Megan Walford
{% endblock %}

tickets/templates/tickets/post_detail.html
{% extends 'base.html' %} {% block content %}
{% load static %}

<div class="masthead">
    <div class="container">
        <div class="row g-0">
            <div class="col-md-6 masthead-text">
                <!-- Post title goes in these h1 tags -->
                <h1 class="post-title">{{ post.title }}</h1>
                <!-- Post author goes before the | the post's created date goes after -->
                <p class="post-subtitle">{{ post.author }} | {{ post.created_on }}</p>
            </div>
            <div class="d-none d-md-block col-md-6 masthead-image">
                <img src="{% static 'images/default.jpg' %}" class="scale" alt="placeholder">
            </div>
        </div>
    </div>
</div>

<div class="container">
    <div class="row">
        <div class="col card mb-4  mt-3 left  top">
            <div class="card-body">
                <!-- The post content goes inside the card-text. -->
                <!-- Use the | safe filter inside the template tags -->
                <p class="card-text">
                    {{ post.content | safe }}
                </p>
            </div>
        </div>
    </div>
</div>

{% endblock content %}

tickets/templates/tickets/ticket_detail.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block content %}
<!-- Ticket Details -->
<div class="container mt-5">
    <div class="row">
        <div class="col-md-8">
            <h2>{{ ticket.title }}</h2>
            <hr>
            <div class="row mb-3">
                <div class="col-md-4 fw-bold">Description:</div>
                <div class="col-md-8">{{ ticket.job_description }}</div>
            </div>
            <div class="row mb-3">
                <div class="col-md-4 fw-bold">Category:</div>
                <div class="col-md-8">{{ ticket.get_job_category_display }}</div>
            </div>
            <div class="row mb-3">
                <div class="col-md-4 fw-bold">Location:</div>
                <div class="col-md-8">{{ ticket.location }}</div>
            </div>
            <div class="row mb-3">
                <div class="col-md-4 fw-bold">Username:</div>
                <div class="col-md-8">{{ ticket.username }}</div>
            </div>
            <div class="row mb-3">
                <div class="col-md-4 fw-bold">Created On:</div>
                <div class="col-md-8">{{ ticket.created_on }}</div>
            </div>
            {% if user.is_authenticated %}
            {% if user.is_superuser or user.is_staff %}
            <form id="completeTicketForm" method="post" action="{% url 'complete_ticket' ticket.slug %}">
                {% csrf_token %}
                <div class="row mb-3">
                    <div class="col-md-4 fw-bold">Ticket Complete:</div>
                    <div class="col-md-8 mt-2">
                        <input type="checkbox" id="is_complete" name="is_complete"
                            {% if ticket.is_complete %}checked{% endif %}
                            onchange="toggleApplyButton()">
                        <button type="submit" id="applyButton" class="mx-4 btn-sm btn-secondary">
                            {% if ticket.is_complete %}Undo Complete{% else %}Complete Ticket{% endif %}
                        </button>
                    </div>
                </div>
            </form>
            {% endif %}
            {% endif %}
            {% if ticket.is_complete %}
            <div class="row mb-3">
                <div class="col-md-4 fw-bold">Completed By:</div>
                <div class="col-md-8">{{ ticket.completed_by }}</div>
            </div>
            <div class="row mb-3">
                <div class="col-md-4 fw-bold">Completed At:</div>
                <div class="col-md-8">{{ ticket.completed_at }}</div>
            </div>
            {% endif %}
            <div class="row mb-3">
                <div class="col-md-4 fw-bold">Last Updated:</div>
                <div class="col-md-8">By {{ ticket.updated_by }} at {{ ticket.updated_on }}</div>
            </div>
            <div class="mt-3 d-flex justify-content-between flex-wrap">
                <a href="{% url 'tickets' %}" class="btn btn-secondary m-3">Return to Tickets</a>
                {% if user.is_authenticated and not ticket.is_complete %}
                {% if ticket.username == user %}
                <div class="m-3 d-flex flex-wrap">
                    <a href="{% url 'update_ticket' ticket.slug %}" class="btn btn-primary me-2 mb-2 mb-md-0">Update
                        Ticket</a>
                    <a href="{% url 'delete_ticket' ticket.slug %}" class="btn btn-danger me-2 mb-2 mb-md-0">Delete
                        Ticket</a>
                </div>
                {% endif %}
                {% endif %}
            </div>
        </div>
    </div>
</div>

<!--Comments Section-->
<div class="container mt-5">
    <div class="row">
        <div class="col-md-8">
            <!--Submitted comments-->
            <h3><i class="far fa-comments"></i> Comments</h3>
            <hr>

            {% if comments %}
            {% for comment in comments %}
            <div class="comment-container" id="comment{{ comment.id }}">
                <div class="comment-header">
                    <span class="comment-username">{{ comment.username }}: </span>
                    <span class="comment-date">{{ comment.created_on }}</span>
                </div>
                <div class="comment-body">{{ comment.body }}</div>
                <div class="d-flex justify-content-end">
                    {% if user.is_authenticated and comment.username == user %}
                    <form id="deleteCommentForm" method="post" action="{% url 'delete_comment' comment.id %}">
                        {% csrf_token %}
                        <button type="submit" class="btn btn-danger"
                            onclick="return confirm('Are you sure you want to delete this comment?')">Delete</button>
                    </form>
                    {% endif %}
                </div>
            </div>
            {% endfor %}
            {% else %}
            <p>No comments just yet...</p>
            {% endif %}
            <hr>

            <!--add new comment-->
            <div>
                {% if user.is_authenticated %}
                <h5>Leave a comment as {{ user.username }}:</h5>
                <form id="commentForm" method="post">
                    {{ comment_form | crispy }}
                    {% csrf_token %}
                    <button type="submit" class="btn btn-primary" style="background-color: #00856f">Submit
                        Comment</button>
                </form>
                {% else %}
                <p>Log in to leave a comment</p>
                {% endif %}
            </div>
        </div>
    </div>
</div>

<script>
    function toggleApplyButton() {
        var checkbox = document.getElementById('is_complete');
        var button = document.getElementById('applyButton');
        if (checkbox.checked) {
            button.style.display = 'inline-block';
        } else {
            button.style.display = 'inline-block';
        }
    }

    // Set the initial state of the button text on page load
    document.addEventListener('DOMContentLoaded', function() {
        var checkbox = document.getElementById('is_complete');
        var button = document.getElementById('applyButton');
        if (checkbox.checked) {
            button.textContent = 'Undo';
        } else {
            button.textContent = 'Apply';
        }
    });

    // Add event listener to change the button text after form submission
    document.getElementById('completeTicketForm').addEventListener('submit', function(event) {
        var checkbox = document.getElementById('is_complete');
        var button = document.getElementById('applyButton');
        if (checkbox.checked) {
            button.textContent = 'Undo';
        } else {
            button.textContent = 'Apply';
        }
    });
</script>

{% endblock content %}

tickets/templates/tickets/ticket_form.html
<!-- Empty field alerts -->
{% if form.non_field_errors %}
<div class="alert alert-danger" role="alert">
    {{ form.non_field_errors }}
</div>
{% endif %}

<!-- Ticket Title -->
<div class="mb-2">
    <label for="title" class="form-label">Title</label>
    <input type="text" class="form-control" id="title" name="title" required>
</div>

<!-- Unique title alert -->
{% if form.errors.title %}
<div class="text-danger">{{ form.errors.title }}</div>
{% endif %}

<!-- Select Job Category -->
<div class="mb-2">
    <label for="job_category" class="form-label">Job Category</label>
    <select class="form-select" id="job_category" name="job_category" required>
        <option value="">Select Job Category</option>
        {% for category_value, category_label in JOB_CATEGORY %}
        <option value="{{ category_value }}">{{ category_label }}</option>
        {% endfor %}
    </select>
</div>

<!-- Enter Job Description -->
<div class="mb-2">
    <label for="job_description" class="form-label">Job Description</label>
    <textarea class="form-control" id="job_description" name="job_description" rows="4" required></textarea>
</div>

<!-- Enter Location -->
<div class="mb-2">
    <label for="location" class="form-label">Location</label>
    <input type="text" class="form-control" id="location" name="location" required>
</div>

<!-- Select Priority -->
<div class="mb-2">
    <label for="priority" class="form-label">Priority</label>
    <select class="form-select" id="priority" name="priority" required>
        <option value="">Select Priority</option>
        {% for priority_value, priority_label in PRIORITY %}
        <option value="{{ priority_value }}">{{ priority_label }}</option>
        {% endfor %}
    </select>
</div>

tickets/templates/tickets/tickets.html
{% extends "base.html" %}
{% load static %}

{% block content %}

<div class="container p-2">
    <div class="row">
        <!--List of open tickets-->
        <div class="col-sm-12 col-md-8">
            <h1 class="py-2">Tickets</h1>
        </div>
        <div class="col-sm-12 col-md-4 d-flex justify-content-end align-items-center">
            {% if user.is_authenticated %}
            <div class="d-flex justify-content-end align-items-center mb-2">
                <a href="{% url 'create_ticket' %}" class="btn btn-primary" style="background-color: #00856f">Create New
                    Ticket</a>
            </div>
            {% else %}
            <div class="d-flex justify-content-end mb-2">
                <a href="{% url 'account_login' %}" class="btn btn-primary" style="background-color: #00856f">Log in to
                    create a ticket</a>
            </div>
            {% endif %}
        </div>

        <div class="row">
            <div class="col-sm-12 col-md-8 mx-auto">
                <!-- Filter section -->
                <form id="filterForm" method="GET">
                    <div class="mb-3 d-flex align-items-end">
                        <div>
                            <label for="sortBy" class="form-label">Sort By:</label>
                            <select class="form-select" id="sortBy" name="sort_by">
                                <option value="priority_high" {% if selected_sort_by == "priority_high" %}selected{% endif %}>
                                    High Priority</option>
                                <option value="priority_low" {% if selected_sort_by == "priority_low" %}selected{% endif %}>
                                        Low Priority</option>
                                <option value="created_newest" {% if selected_sort_by == "created_newest" %}selected{% endif %}>
                                    Newest Created</option>
                                <option value="created_oldest" {% if selected_sort_by == "created_oldest" %}selected{% endif %}>
                                        Oldest Created</option>
                                <option value="completed" {% if selected_sort_by == "completed" %}selected{% endif %}>Completed</option>
                            </select>
                        </div>
                    </div>
                </form>

                <!--User tickets only checkbox-->
                <form method="get" action="{% url 'tickets' %}" class="text-end mb-2" id="ownTicketsForm">
                    <input type="checkbox" id="own_tickets" name="own_tickets" {% if show_own_tickets %}checked{% endif %}>
                    <label for="own_tickets">Show Only My Tickets</label>
                    <input type="submit" value="Apply Filter" style="display: none;">
                </form>

                <!--List of tickets-->
                {% for ticket in object_list %}
                <div class="card mb-2">
                    <div class="card-body">
                        <a href="{% url 'ticket_detail' ticket.slug %}">
                            <h4 class="card-title">{{ ticket.title }}</h4>
                        </a>
                        {% if ticket.is_complete %}
                        <p class="text-end mb-0">Completed: {{ ticket.completed_at }}</p>
                        {% else %}
                        <p class="text-end mb-0 priority-{{ ticket.priority }}">
                            Priority: {{ ticket.get_priority_display }}
                        </p>
                        <p class="text-end mb-0">Created: {{ ticket.created_on }}</p>
                        {% endif %}
                    </div>
                </div>
                {% endfor %}

                <!--Pagination-->
                {% if is_paginated %}
                <nav aria-label="Page navigation">
                    <ul class="pagination justify-content-center">
                        {% if page_obj.has_previous %}
                        <li class="page-item {% if page_obj.has_previous %} {% else %} disabled {% endif %}">
                            <a class="page-link"
                                href="?page=1{% if selected_sort_by %}&sort_by={{ selected_sort_by }}{% endif %}">&laquo;
                                Prev</a>
                        </li>
                        {% endif %}
                        {% if page_obj.has_next %}
                        <li class="page-item {% if page_obj.has_next %} {% else %} disabled {% endif %}">
                            <a class="page-link"
                                href="?page={{ page_obj.paginator.num_pages }}{% if selected_sort_by %}&sort_by={{ selected_sort_by }}{% endif %}">Next
                                &raquo;</a>
                        </li>
                        {% endif %}
                    </ul>
                </nav>
                {% endif %}
            </div>
        </div>
    </div>
</div>

{% endblock %}